### ISSUE TITLE
ActiveFedora::UnknownAttributeError

### ISSUE THREAD

**Issue by jayanthdeejay** [gwu-libraries/batch-loader#3]
We at our institution are using this tool to batch ingest ETDs onto our servers. Great job developing this. 

One of the metadata fields in our csv is [identifier](https://github.com/samvera/hyrax/blob/ee34254e986a2fc66eb0c09df9a14fa3748735cb/app/models/concerns/hyrax/basic_metadata.rb#L28). AF doesn't recognize it for some reason. Any help!?

```shell
rake aborted!
ActiveFedora::UnknownAttributeError: unknown attribute 'identifier' for Etd.
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/attribute_assignment.rb:50:in `_assign_attribute'
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/attribute_assignment.rb:45:in `block in _assign_attributes'
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/attribute_assignment.rb:44:in `each'
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/attribute_assignment.rb:44:in `_assign_attributes'
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/attribute_assignment.rb:38:in `assign_attributes'
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/attribute_assignment.rb:9:in `attributes='
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/attributes/serializers.rb:24:in `attributes='
/Users/xyz/dev/rails/test/digitalwpi/lib/tasks/gwss.rake:206:in `ingest_etd'
/Users/xyz/dev/rails/test/digitalwpi/lib/tasks/gwss.rake:129:in `block (2 levels) in <top (required)>'
/Users/xyz/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/xyz/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/xyz/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => gwss:ingest_etd
(See full trace by running task with --trace)
Traceback (most recent call last):
  File "batch_loader.py", line 165, in <module>
    raise e
  File "batch_loader.py", line 161, in <module>
    config.ingest_depositor)
  File "batch_loader.py", line 120, in repo_import
    output = subprocess.check_output(command, cwd=ingest_path)
  File "/Users/xyz/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/xyz/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
```

**Comment by kerchner** [comment]
@jayanthdeejay Hi Jay, thanks for the ticket, I'll take a look.  What institution are you with?

**Comment by jayanthdeejay** [comment]
@kerchner Worcester Polytechnic Institute

**Comment by jayanthdeejay** [comment]
I have been working on this since this morning. I briefly encountered the error that I mentioned above. Now, I'm not getting the error but the process is stuck at 

```shell
webapp@arcubuntu18template:/datastorage/batch-loader$ python3 batch_loader.py /datastorage/Available/test.csv
INFO:__main__:Loading 1 object from /datastorage/Available/test.csv
INFO:__main__:Importing ['Performance-Based Codes: Economics, Documentation, and Design'].
INFO:__main__:Command is: rvmsudo RAILS_ENV=development rake gwss:ingest_etd -- --manifest=/tmp/tmpxto90q_c/metadata.json --primaryfile=/datastorage/Available/etd-051199-173528/averill.pdf --depositor=xyz@wpi.edu
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. Run:

    export rvmsudo_secure_path=1

to avoid the warning, put it in shell initialization file to make it persistent.

In case there is no `secure_path` in `/etc/sudoers`. Run:

    export rvmsudo_secure_path=0

to avoid the warning, put it in shell initialization file to make it persistent.
[sudo] password for webapp:
```
There is just one entry the test.csv file.... I tested this locally and everything worked just fine... When testing it on dev server, I'm facing these issues. Thank YOU. Your tool is saving me ton of time! :)

**Comment by jayanthdeejay** [comment]
Found the issue. My input CSV file had a [BOM](https://stackoverflow.com/questions/204765/elegant-way-to-search-for-utf-8-files-with-bom). Thank you.

**Comment by kerchner** [comment]
Ah, glad you found the issue @jayanthdeejay
